# Generated by Django 5.2 on 2025-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courtroom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="current_phase",
            field=models.CharField(default="opening", max_length=20),
        ),
        migrations.AddField(
            model_name="case",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
        migrations.AddField(
            model_name="caselog",
            name="phase",
            field=models.CharField(default="opening", max_length=20),
        ),
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="caselog",
            name="case_name",
            field=models.CharField(max_length=255),
        ),
    ]
