# Generated by Django 5.2 on 2025-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courtroom", "0002_case_current_phase_case_status_caselog_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="verdict_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="caselog",
            name="is_verdict",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="caselog",
            name="verdict_confidence",
            field=models.FloatField(default=0.0),
        ),
    ]
