# Generated by Django 5.2 on 2025-04-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courtroom", "0003_case_verdict_text_caselog_is_verdict_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="verdict_text",
        ),
        migrations.RemoveField(
            model_name="caselog",
            name="is_verdict",
        ),
        migrations.RemoveField(
            model_name="caselog",
            name="verdict_confidence",
        ),
    ]
